# Generated by Django 5.2.17 on 2026-10-03 16:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='ISO 4217 code, e.g. KES', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=True, help_text='New wallets can be opened in this currency.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text="Order in the app's currency lists.")),
                ('min_transfer', models.DecimalField(decimal_places=2, help_text='Smallest amount per transfer, payment or withdrawal.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_transfer', models.DecimalField(decimal_places=2, help_text='Largest amount per transfer, payment or withdrawal.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('signup_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credited to each new personal wallet in this currency, from the Promotions system account. Keep at 0 unless running a promotion.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('statement_max_days', models.PositiveSmallIntegerField(help_text='Longest period one statement may cover.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3660)])),
                ('invitation_expiry_days', models.PositiveSmallIntegerField(help_text='How long a business invitation link works.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('session_timeout_minutes', models.PositiveSmallIntegerField(help_text='The app signs the user out after this much inactivity.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('budget_needs_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('budget_wants_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('budget_savings_percent', models.PositiveSmallIntegerField(help_text="The budget planner's guideline; the three must add up to 100.", validators=[django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(help_text='Preselected when opening a wallet.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_settings.currency')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platform settings',
                'verbose_name_plural': 'platform settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='platform_settings_single_row')],
            },
        ),
    ]
