# Generated by Django 5.2.17 on 2026-10-04 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0002_initial_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payroll_reversal_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='How many days after payday a business may take back a salary paid in error.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
    ]
