# Generated by Django 5.2.17 on 2026-10-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='books_category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
