# Generated by Django 5.2.17 on 2026-10-04 15:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_one_cashbook_per_business'),
        ('organizations', '0005_payment_constraints'),
        ('payroll', '0002_remove_payslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='beneficiary_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('VENDOR', 'Vendor'), ('CONTRACTOR', 'Contractor'), ('LANDLORD', 'Landlord'), ('SERVICE_PROVIDER', 'Service provider'), ('UTILITY', 'Utility'), ('OTHER', 'Other')], max_length=16)),
                ('books_category', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(choices=[('FLUXPAY', 'FluxPay account'), ('MPESA_MOBILE', 'M-Pesa phone number'), ('MPESA_PAYBILL', 'M-Pesa paybill'), ('MPESA_TILL', 'M-Pesa till (Buy Goods)'), ('BANK', 'Bank transfer')], max_length=16)),
                ('account_number', models.CharField(blank=True, max_length=10)),
                ('mpesa_phone', models.CharField(blank=True, max_length=16)),
                ('paybill_number', models.CharField(blank=True, max_length=7)),
                ('paybill_account', models.CharField(blank=True, max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=7)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('bank_branch', models.CharField(blank=True, max_length=80)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=34)),
                ('bank_swift_code', models.CharField(blank=True, max_length=11)),
                ('details_changed_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('details_changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='organizations.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'beneficiaries',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.beneficiary'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('worker__isnull', True), ('beneficiary__isnull', True), _connector='OR'), name='payment_to_worker_or_beneficiary'),
        ),
        migrations.AddConstraint(
            model_name='beneficiary',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), condition=models.Q(('is_active', True)), name='unique_active_beneficiary_name'),
        ),
    ]
