# Generated by Django 5.2.17 on 2026-10-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_beneficiaries'),
        ('payments', '0004_mpesa_and_bank_payouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_payment', to='payments.externalpayment'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='kind',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('VENDOR', 'Vendor'), ('CONTRACTOR', 'Contractor'), ('LANDLORD', 'Landlord'), ('SERVICE_PROVIDER', 'Service provider'), ('UTILITY', 'Utility'), ('OWN_ACCOUNT', "The business's own account"), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='destination_account_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('ALLOWANCE', 'Allowance'), ('BONUS', 'Bonus'), ('COMMISSION', 'Commission'), ('OTHER_WORKER', 'Other worker payment'), ('SUPPLIER', 'Supplier payment'), ('VENDOR', 'Vendor payment'), ('CONTRACTOR', 'Contractor payment'), ('EXPENSE', 'Business expense'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other payment')], max_length=12),
        ),
    ]
