# Generated by Django 5.2.17 on 2026-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_external_payouts_and_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='worker_join_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
