# Generated by Django 5.2.17 on 2026-10-04 12:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text='How staff will recognise it, e.g. "Equity Bank – customer funds".', max_length=80
                    ),
                ),
                ("bank_name", models.CharField(max_length=80)),
                ("account_number", models.CharField(max_length=40)),
                ("branch", models.CharField(blank=True, max_length=80)),
                ("currency", models.CharField(max_length=3)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("SAFEGUARDING", "Customer funds (safeguarding)"),
                            ("OPERATING", "FluxPay's own money (operating)"),
                        ],
                        help_text="Customer deposits may only be banked in a safeguarding account, kept apart from FluxPay's own money.",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("name", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("last", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("statement_date", models.DateField()),
                ("statement_balance", models.DecimalField(decimal_places=2, max_digits=16)),
                ("cashbook_balance", models.DecimalField(decimal_places=2, max_digits=16)),
                ("uncleared_receipts", models.DecimalField(decimal_places=2, max_digits=16)),
                ("uncleared_payments", models.DecimalField(decimal_places=2, max_digits=16)),
                ("entries_cleared", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="accounting.bankaccount",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-statement_date", "-created_at"),
                "permissions": [("reconcile_bank", "Can reconcile bank accounts")],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(editable=False, max_length=12, unique=True)),
                ("date", models.DateField(help_text="The accounting date: the day the money moved.")),
                ("currency", models.CharField(editable=False, max_length=3)),
                ("memo", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CASHBOOK", "Cashbook"),
                            ("ALLOCATION", "Wallet top-up / correction"),
                            ("WALLET", "Wallet activity"),
                            ("MANUAL", "Manual journal"),
                            ("OPENING", "Opening balances"),
                            ("REVERSAL", "Reversal"),
                        ],
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal entry",
                "verbose_name_plural": "journals",
                "ordering": ("-date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(help_text="Accounts are listed in code order, e.g. 5910 for rent.", max_length=10),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("role", models.CharField(blank=True, editable=False, max_length=60)),
                ("is_control", models.BooleanField(default=False, editable=False)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ledger account",
                "verbose_name_plural": "chart of accounts",
                "ordering": ("currency", "code"),
                "permissions": [
                    ("view_financial_reports", "Can view financial reports"),
                    ("post_journal", "Can post manual journals"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code", "currency"), name="ledger_account_unique_code"),
                    models.UniqueConstraint(
                        condition=models.Q(("role", ""), _negated=True),
                        fields=("role", "currency"),
                        name="ledger_account_unique_role",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="ledger_account",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="accounting.ledgeraccount",
            ),
        ),
        migrations.CreateModel(
            name="AccountingSettings",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                (
                    "books_closed_until",
                    models.DateField(
                        blank=True,
                        help_text="Nothing can be posted on or before this date. Set it once a month's accounts are final.",
                        null=True,
                    ),
                ),
                (
                    "require_second_person",
                    models.BooleanField(
                        default=False,
                        help_text="Segregation of duties: the person who credits a customer's wallet must not be the person who recorded the bank receipt.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "accounting settings",
                "verbose_name_plural": "accounting settings",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="accounting_settings_single_row")
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="accounting.journalentry"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="accounting.ledgeraccount"
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("debit__gt", 0), ("credit", 0)),
                            models.Q(("credit__gt", 0), ("debit", 0)),
                            _connector="OR",
                        ),
                        name="journal_line_one_side",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CashbookEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(editable=False, max_length=12, unique=True)),
                (
                    "direction",
                    models.CharField(choices=[("RECEIPT", "Money in"), ("PAYMENT", "Money out")], max_length=7),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_DEPOSIT", "Customer deposit"),
                            ("CAPITAL", "Owner's capital"),
                            ("INTEREST", "Interest from the bank"),
                            ("OTHER_INCOME", "Other income"),
                            ("CUSTOMER_PAYOUT", "Customer withdrawal"),
                            ("BANK_CHARGES", "Bank charges"),
                            ("EXPENSE", "Business expense"),
                            ("DRAWINGS", "Owner's drawings"),
                            ("BANK_TRANSFER", "Transfer between FluxPay bank accounts"),
                            ("REVERSAL", "Reversal of an earlier entry"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The date the money moved in the bank (as on the bank statement)."),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("counterparty", models.CharField(help_text="Who paid in, or who was paid.", max_length=120)),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        help_text="Deposit slip, cheque or bank transaction number, to match the statement.",
                        max_length=60,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "allocated",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=16),
                ),
                (
                    "cleared_on",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="The bank statement date this entry was matched to.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="accounting.bankaccount"
                    ),
                ),
                (
                    "counterpart",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.cashbookentry",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="accounting.cashbookentry",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashbook_entries",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashbook_entries",
                        to="accounting.ledgeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "cashbook entry",
                "verbose_name_plural": "cashbook",
                "ordering": ("-date", "-created_at"),
                "permissions": [("record_cashbook", "Can record bank receipts and payments")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("allocated__gte", 0), ("allocated__lte", models.F("amount"))),
                        name="cashbook_allocation_within_amount",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("bank_name", "account_number"), name="bank_account_unique_number"
            ),
        ),
    ]
