# Generated by Django 5.2.17 on 2026-10-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_settings_and_opening_balances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbookentry',
            options={'ordering': ('-date', '-created_at'), 'permissions': [('record_cashbook', 'Can record bank receipts and payments')], 'verbose_name': 'cashbook entry', 'verbose_name_plural': 'cashbook entries'},
        ),
    ]
