# Generated by Django 5.2.17 on 2026-10-04 13:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_cashbook_names'),
        ('banking', '0008_transfer_reverses'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'Money in'), ('OUT', 'Money out')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('counterparty', models.CharField(blank=True, max_length=150)),
                ('counterparty_account', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=40)),
                ('source', models.CharField(choices=[('OPENING', 'Opening balance'), ('TRANSFER', 'Transfer'), ('PAYROLL', 'Payroll'), ('PAYROLL_REVERSAL', 'Payroll reversal'), ('DEPOSIT', 'Deposit at FluxPay'), ('CORRECTION', 'Correction by FluxPay'), ('WITHDRAWAL', 'Cash withdrawal')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'business cashbook entry',
                'verbose_name_plural': 'business cashbooks',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='ledgeraccount',
            name='ledger_account_unique_code',
        ),
        migrations.RemoveConstraint(
            model_name='ledgeraccount',
            name='ledger_account_unique_role',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='organization',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='organization',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='number',
            field=models.CharField(editable=False, max_length=12),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('number',), name='journal_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'number'), name='business_journal_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code', 'currency'), name='ledger_account_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('role', ''), _negated=True), ('organization__isnull', True)), fields=('role', 'currency'), name='ledger_account_unique_role'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'code', 'currency'), name='business_ledger_account_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('role', ''), _negated=True), ('organization__isnull', False)), fields=('organization', 'role', 'currency'), name='business_ledger_account_unique_role'),
        ),
        migrations.AddField(
            model_name='businessentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_entries', to='accounting.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='businessentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_entries', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='businessentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='businessentry',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_entries', to='banking.account'),
        ),
        migrations.AddIndex(
            model_name='businessentry',
            index=models.Index(fields=['organization', 'wallet', 'date'], name='accounting__organiz_56d0dd_idx'),
        ),
    ]
