# Generated by Django 5.2.17 on 2026-10-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_business_opening_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentry',
            name='source',
            field=models.CharField(choices=[('OPENING', 'Opening balance'), ('TRANSFER', 'Transfer'), ('PAYROLL', 'Payroll'), ('PAYROLL_REVERSAL', 'Payroll reversal'), ('REVERSAL', 'Payment reversal'), ('DEPOSIT', 'Deposit at FluxPay'), ('CORRECTION', 'Correction by FluxPay'), ('WITHDRAWAL', 'Cash withdrawal')], max_length=16),
        ),
    ]
