# Generated by Django 5.2.17 on 2026-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_businessentry_reversal_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentry',
            name='source',
            field=models.CharField(choices=[('OPENING', 'Opening balance'), ('TRANSFER', 'Transfer'), ('PAYROLL', 'Payroll'), ('PAYROLL_REVERSAL', 'Payroll reversal'), ('REVERSAL', 'Payment reversal'), ('PROVIDER_DEPOSIT', 'Deposit by M-Pesa'), ('PAYOUT', 'Paid out by M-Pesa or bank'), ('PAYOUT_RETURNED', 'Payout returned'), ('DEPOSIT', 'Deposit at FluxPay'), ('CORRECTION', 'Correction by FluxPay'), ('WITHDRAWAL', 'Cash withdrawal')], max_length=16),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='category',
            field=models.CharField(choices=[('CUSTOMER_DEPOSIT', 'Customer deposit'), ('CAPITAL', "Owner's capital"), ('INTEREST', 'Interest from the bank'), ('OTHER_INCOME', 'Other income'), ('CUSTOMER_PAYOUT', 'Customer withdrawal'), ('BANK_PAYOUT', 'Bank payout requested in the app'), ('BANK_CHARGES', 'Bank charges'), ('EXPENSE', 'Business expense'), ('DRAWINGS', "Owner's drawings"), ('BANK_TRANSFER', 'Transfer between FluxPay bank accounts'), ('REVERSAL', 'Reversal of an earlier entry')], max_length=16),
        ),
    ]
