# Generated by Django 5.2.17 on 2026-10-06 15:32

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_bank_and_mpesa_payouts'),
        ('organizations', '0008_worker_join_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('BILL', 'Bill to pay'), ('INVOICE', 'Invoice to collect')], max_length=8)),
                ('number', models.CharField(max_length=20)),
                ('party', models.CharField(help_text='The supplier (bill) or customer (invoice).', max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Not paid'), ('PART_PAID', 'Part paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.ledgeraccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organizations.organization')),
            ],
            options={
                'ordering': ('-issue_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payment', to='accounting.businessentry')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.invoice')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('previous_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='invoice_number_unique_per_business'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('amount'))), name='invoice_not_overpaid'),
        ),
    ]
