# Generated by Django 5.2.17 on 2026-10-03 11:38

import banking.models
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        default=banking.models.generate_account_number,
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="Main Wallet", max_length=60)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "Kenyan Shilling"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="KES",
                        max_length=3,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")], max_length=6
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRANSFER_IN", "Transfer received"),
                            ("TRANSFER_OUT", "Transfer sent"),
                            ("BONUS", "Bonus"),
                            ("DEPOSIT", "Deposit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="COMPLETED",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=14)),
                ("counterparty_name", models.CharField(blank=True, max_length=150)),
                ("counterparty_account", models.CharField(blank=True, max_length=10)),
                ("description", models.CharField(blank=True, max_length=140)),
                ("reference", models.CharField(db_index=True, max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("note", models.CharField(blank=True, max_length=140)),
                ("reference", models.CharField(max_length=24, unique=True)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
