# Generated by Django 5.2.17 on 2026-10-03 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='account_balance_non_negative',
        ),
        migrations.AddField(
            model_name='account',
            name='system_key',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('TRANSFER_IN', 'Transfer received'), ('TRANSFER_OUT', 'Transfer sent'), ('BONUS', 'Bonus'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal returned')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0), ('system_key__isnull', False), _connector='OR'), name='account_balance_non_negative'),
        ),
    ]
