# Generated by Django 5.2.17 on 2026-10-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_system_key_withdrawal_categories'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='organizations.organization'),
        ),
    ]
