# Generated by Django 5.2.17 on 2026-10-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_account_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
