# Generated by Django 5.2.17 on 2026-10-04 10:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_account_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('TRANSFER_IN', 'Transfer received'), ('TRANSFER_OUT', 'Transfer sent'), ('BONUS', 'Bonus'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal returned'), ('ADJUSTMENT', 'Adjustment by FluxPay')], max_length=20),
        ),
        migrations.CreateModel(
            name='ManualAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CREDIT', 'Top-up (add money)'), ('DEBIT', 'Correction (take money back)')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(help_text='Why, for the audit trail, e.g. "Cash deposited at the Nairobi office, receipt 1042".', max_length=255)),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='banking.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('post_adjustment', 'Can top up or correct customer wallets')],
            },
        ),
    ]
