# Generated by Django 5.2.17 on 2026-10-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('banking', '0006_manual_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualadjustment',
            name='cashbook_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='accounting.cashbookentry', verbose_name='bank receipt'),
        ),
        migrations.AlterField(
            model_name='manualadjustment',
            name='kind',
            field=models.CharField(choices=[('CREDIT', 'Top-up (credit the wallet from a bank receipt)'), ('DEBIT', 'Correction (return money to the bank receipt)'), ('PAYOUT', 'Cash withdrawal paid from the bank')], max_length=6),
        ),
    ]
