# Generated by Django 5.2.17 on 2026-10-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_manualadjustment_cashbook_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='banking.transfer'),
        ),
    ]
