# Generated by Django 5.2.17 on 2026-10-04 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_transfer_reverses'),
        ('organizations', '0002_payment_books_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization',), name='one_cashbook_per_business'),
        ),
    ]
