# Generated by Django 5.2.17 on 2026-10-03 13:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0003_account_system_key_withdrawal_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('IN', 'Deposit'), ('OUT', 'Withdrawal')], max_length=3)),
                ('rail', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer'), ('FAKE', 'Fake (tests and local dev)')], max_length=10)),
                ('method', models.CharField(choices=[('STK', 'M-Pesa STK Push'), ('C2B', 'M-Pesa Paybill'), ('B2C', 'M-Pesa B2C'), ('PAYPAL_ORDER', 'PayPal Checkout'), ('PAYPAL_PAYOUT', 'PayPal Payout'), ('BANK_OUT', 'Bank payout'), ('FAKE_IN', 'Fake deposit'), ('FAKE_OUT', 'Fake payout')], max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('HELD', 'Held'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed')], db_index=True, default='CREATED', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('provider_ref', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_payments', to='banking.account')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rail', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer'), ('FAKE', 'Fake (tests and local dev)')], max_length=10)),
                ('event_id', models.CharField(max_length=128)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.externalpayment')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='externalpayment',
            index=models.Index(fields=['status', 'updated_at'], name='payments_ex_status_fa3473_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('rail', 'provider_ref'), name='unique_payment_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='externalpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('initiated_by__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('initiated_by', 'idempotency_key'), name='unique_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('rail', 'event_id'), name='unique_webhook_event'),
        ),
    ]
