# Generated by Django 5.2.17 on 2026-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpayment',
            name='method',
            field=models.CharField(choices=[('PAYPAL_ORDER', 'PayPal Checkout'), ('PAYPAL_PAYOUT', 'PayPal Payout'), ('BANK_OUT', 'Bank payout'), ('FAKE_IN', 'Fake deposit'), ('FAKE_OUT', 'Fake payout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='externalpayment',
            name='rail',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer'), ('FAKE', 'Fake (tests only)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='rail',
            field=models.CharField(choices=[('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer'), ('FAKE', 'Fake (tests only)')], max_length=10),
        ),
    ]
