# Generated by Django 5.2.17 on 2026-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_externalpayment_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalpayment',
            options={'ordering': ('-created_at',), 'permissions': [('settle_payout', 'Can confirm or fail payouts by hand (bank payouts, unanswered M-Pesa)')]},
        ),
        migrations.AlterField(
            model_name='externalpayment',
            name='method',
            field=models.CharField(choices=[('MPESA_STK', 'M-Pesa STK Push'), ('MPESA_B2C', 'M-Pesa to a phone'), ('MPESA_PAYBILL', 'M-Pesa to a paybill'), ('MPESA_TILL', 'M-Pesa to a till'), ('PAYPAL_ORDER', 'PayPal Checkout'), ('PAYPAL_PAYOUT', 'PayPal Payout'), ('BANK_OUT', 'Bank payout (sent by FluxPay staff)'), ('FAKE_IN', 'Fake deposit'), ('FAKE_OUT', 'Fake payout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='externalpayment',
            name='rail',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer'), ('FAKE', 'Fake (tests only)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='rail',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer'), ('FAKE', 'Fake (tests only)')], max_length=10),
        ),
    ]
