# Generated by Django 5.2.17 on 2026-10-04 13:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_businessentry_and_more'),
        ('banking', '0008_transfer_reverses'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Waiting for approval'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_run', to='accounting.businessentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_runs', to='organizations.organization')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='banking.account')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=80)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='organizations.organization')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='banking.account')),
            ],
            options={
                'ordering': ('wallet__owner__full_name',),
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Not paid yet'), ('PAID', 'Paid'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrun')),
                ('reversal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payslip', to='banking.transfer')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='banking.transfer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.worker')),
            ],
            options={
                'ordering': ('worker__wallet__owner__full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('organization', 'wallet'), name='unique_worker_wallet'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('pay_run', 'worker'), name='unique_payslip_per_run'),
        ),
    ]
