# Generated by Django 5.2.17 on 2026-10-05 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_last_counter',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_pending_secret',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name='MfaRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'code_hash'], name='users_mfare_user_id_239ba0_idx')],
            },
        ),
    ]
